// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: rpc_create_publisher.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePublisherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreatePublisherRequest) Reset() {
	*x = CreatePublisherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_publisher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublisherRequest) ProtoMessage() {}

func (x *CreatePublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_publisher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublisherRequest.ProtoReflect.Descriptor instead.
func (*CreatePublisherRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePublisherRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreatePublisherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publisher *Publisher `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
}

func (x *CreatePublisherResponse) Reset() {
	*x = CreatePublisherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_publisher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePublisherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublisherResponse) ProtoMessage() {}

func (x *CreatePublisherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_publisher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublisherResponse.ProtoReflect.Descriptor instead.
func (*CreatePublisherResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePublisherResponse) GetPublisher() *Publisher {
	if x != nil {
		return x.Publisher
	}
	return nil
}

var File_rpc_create_publisher_proto protoreflect.FileDescriptor

var file_rpc_create_publisher_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2c, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x46, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x72, 0x69, 0x74, 0x65, 0x63, 0x68, 0x69, 0x65,
	0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x72, 0x65, 0x70, 0x6f, 0x2d, 0x73, 0x76, 0x63, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_publisher_proto_rawDescOnce sync.Once
	file_rpc_create_publisher_proto_rawDescData = file_rpc_create_publisher_proto_rawDesc
)

func file_rpc_create_publisher_proto_rawDescGZIP() []byte {
	file_rpc_create_publisher_proto_rawDescOnce.Do(func() {
		file_rpc_create_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_publisher_proto_rawDescData)
	})
	return file_rpc_create_publisher_proto_rawDescData
}

var file_rpc_create_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_publisher_proto_goTypes = []interface{}{
	(*CreatePublisherRequest)(nil),  // 0: pb.CreatePublisherRequest
	(*CreatePublisherResponse)(nil), // 1: pb.CreatePublisherResponse
	(*Publisher)(nil),               // 2: pb.Publisher
}
var file_rpc_create_publisher_proto_depIdxs = []int32{
	2, // 0: pb.CreatePublisherResponse.publisher:type_name -> pb.Publisher
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_publisher_proto_init() }
func file_rpc_create_publisher_proto_init() {
	if File_rpc_create_publisher_proto != nil {
		return
	}
	file_publisher_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_publisher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePublisherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_publisher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePublisherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_publisher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_publisher_proto_goTypes,
		DependencyIndexes: file_rpc_create_publisher_proto_depIdxs,
		MessageInfos:      file_rpc_create_publisher_proto_msgTypes,
	}.Build()
	File_rpc_create_publisher_proto = out.File
	file_rpc_create_publisher_proto_rawDesc = nil
	file_rpc_create_publisher_proto_goTypes = nil
	file_rpc_create_publisher_proto_depIdxs = nil
}
